// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhTupEyUYAa1RKtwcykf-C2P77CC8eT0g',
    appId: '1:50715646403:web:243cdde9c98f2cebc00576',
    messagingSenderId: '50715646403',
    projectId: 'teste-bd470',
    authDomain: 'teste-bd470.firebaseapp.com',
    storageBucket: 'teste-bd470.firebasestorage.app',
    measurementId: 'G-HWDEDDRZGY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDK2XHqZ43TntxTC198VRRqySvi1eNT8HU',
    appId: '1:50715646403:android:89d36d62f2866071c00576',
    messagingSenderId: '50715646403',
    projectId: 'teste-bd470',
    storageBucket: 'teste-bd470.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBr9lapo1sNHE3ShgC3cfNTs4WSRqwmAu0',
    appId: '1:50715646403:ios:2a269c423f943f10c00576',
    messagingSenderId: '50715646403',
    projectId: 'teste-bd470',
    storageBucket: 'teste-bd470.firebasestorage.app',
    iosBundleId: 'com.example.testeflutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBr9lapo1sNHE3ShgC3cfNTs4WSRqwmAu0',
    appId: '1:50715646403:ios:2a269c423f943f10c00576',
    messagingSenderId: '50715646403',
    projectId: 'teste-bd470',
    storageBucket: 'teste-bd470.firebasestorage.app',
    iosBundleId: 'com.example.testeflutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDhTupEyUYAa1RKtwcykf-C2P77CC8eT0g',
    appId: '1:50715646403:web:4c43cd032f9728d7c00576',
    messagingSenderId: '50715646403',
    projectId: 'teste-bd470',
    authDomain: 'teste-bd470.firebaseapp.com',
    storageBucket: 'teste-bd470.firebasestorage.app',
    measurementId: 'G-ZRK5YZMZW5',
  );
}
